[package]
name = "stackable-krb5-provision-keytab"
authors = ["Stackable GmbH <info@stackable.de>"]
description = "CLI for provisioning Kerberos keytabs"
license = "OSL-3.0"
version = "0.0.0-dev"
edition = "2021"
repository = "https://github.com/stackabletech/secret-operator"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
krb5 = { path = "../krb5" }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
snafu = "0.7.4"
tokio = { version = "1.25.0", features = ["io-util", "process"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
ldap3 = { version = "0.11.1", default-features = false, features = ["gssapi", "tls", "sync"] }
byteorder = "1.4.3"
